name: CI pipeline
on: 
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v6
      - name : set up dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: restore 
        run: dotnet restore helloapp/helloapp.csproj
      - name: build 
        run: dotnet build helloapp/helloapp.csproj --no-restore 
      - name: test 
        run: dotnet test 
  
      