name: CI pipeline
on: 
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v6
      - name : set up dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: restore 
        run: dotnet restore helloapp/helloapp.csproj
      - name: build 
        run: dotnet build helloapp/helloapp.csproj --no-restore 
      - name: test 
        run: dotnet test helloapp/helloapp.csproj 
      - name: publish
        run: dotnet publish helloapp/helloapp.csproj --no-restore

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
         name: my-artifact
         path: helloapp/bin/Release/net9.0/publish/